spring.application.name=graphDemo
server.port=8096
spring.datasource.url=jdbc:mysql://localhost:3306/graph
spring.datasource.username=root
spring.datasource.password=ameen26@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.multipart=DEBUG
logging.level.graphQL=DEBUG

# Enable GraphiQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

# Enable Playground
spring.graphql.playground.enabled=true
spring.graphql.playground.path=/playground

# Enable Voyager
spring.graphql.voyager.enabled=true
spring.graphql.voyager.path=/voyager

# Enable Altair UI
graphql.altair.enabled=true
graphql.altair.path=/altair
graphql.altair.endpoint=/graphql
graphql.altair.headers.Authorization=Bearer your-token-here
graphql.altair.subscriptionsEnabled=false
